spring:
  application:
    name: caller-service
server:
  port: 8090

resilience4j:
  circuitbreaker:
    instances:
      # 설정의 고유 이름. 코드의 @CircuitBreaker 어노테이션에서 이 이름을 사용한다.
      productService:
        sliding-window-type: count-based # 최근 요청 횟수를 기반으로 실패율을 계산한다.
        sliding-window-size: 5          # 실패율을 계산할 최근 요청의 개수를 5개로 지정한다.
        failure-rate-threshold: 50       # 실패율이 50% 이상이면 서킷을 open 상태로 변경한다. (10개 중 5개 이상 실패 시)
        wait-duration-in-open-state: 10s # open 상태를 10초간 유지한다. 이 시간이 지나면 half-open 상태가 된다.
        permitted-number-of-calls-in-half-open-state: 2 # half-open 상태에서 2개의 테스트 요청을 보낸다.
        automatic-transition-from-open-to-half-open-enabled: true # open 상태에서 half-open 상태로 자동 전환을 활성화한다.
management:
  endpoints:
    web:
      exposure:
        include: health, circuitbreakers